version: '3.9'

services:
  app:
    build: server
    image: ${APP_NAME}-app
    container_name: ${APP_NAME}-app
    env_file:
      - .env
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ../../:/app
    ports:
      - ${APP_PORT}:80
    networks:
      net:
        aliases:
          - ${APP_NAME}-app
    entrypoint: /scripts/init_container.sh
  db:
    image: ${APP_NAME}-db
    build: db
    container_name: ${APP_NAME}-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - ${DB_PORT}:3306
#    volumes:
#      - /db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      net:
        aliases:
          - "${APP_NAME}-db"


networks:
  net:
    driver: bridge
  
